articles = {'Философия': {1: 'https://cyberleninka.ru/article/n/neistovyy-u-vrat-poezii/viewer',
                          2: 'https://cyberleninka.ru/article/n/psihologicheskiy-podhod-k-ideologii-ot-freyda-k-pareto/viewer',
                          3: 'https://cyberleninka.ru/article/n/filosofiya-kanta-i-lingvisticheskoe-kantianstvo/viewer',
                          4: 'https://cyberleninka.ru/article/n/s-zhizhek-o-bessoznatelnyh-predposylkah-ideologii/viewer',
                          5: 'https://cyberleninka.ru/article/n/svoboda-voli-vse-za-i-protiv/viewer'},
            'IT': {1: 'https://cyberleninka.ru/article/n/algoritm-obnaruzheniya-rfid-dublikatov/viewer',
                   2: 'https://cyberleninka.ru/article/n/razrabotka-algoritma-web-autentifikatsii-pri-pomoschi-rasshireniya-metamask/viewer',
                   3: 'https://cyberleninka.ru/article/n/tehnologiya-vdi/viewer',
                   4: 'https://habr.com/ru/post/245325/',
                   5: 'https://habr.com/ru/post/332714/',
                   6: 'https://cyberleninka.ru/article/n/zaschischennaya-otpravka-soobscheniy-po-mesh-seti-na-osnove-bluetooth/viewer',
                   7: 'https://cyberleninka.ru/article/n/razrabotka-detsentralizovannogo-dns-servera-na-osnove-tehnologii-blokcheyn/viewer',
                   8: 'https://cyberleninka.ru/article/n/szhatie-dannyh-algoritm-haffmana/viewer'},
            'Литература': {1: 'https://cyberleninka.ru/article/n/karnavalizatsiya-v-romane-v-gyugo-chelovek-kotoryy-smeyotsya/viewer',
                           2: 'https://cyberleninka.ru/article/n/filosofiya-vlasti-v-prestuplenii-i-nakazanii-f-m-dostoevskogo/viewer'},
            'Другое': {1: 'https://cyberleninka.ru/article/n/intellektualy-i-vlast-kazus-v-gyugo/viewer'}}